Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -48,7 +48,6 @@ deploy-uat:
   script:
     - install_dependencies
     - download_chart
-    - ensure_namespace
     - install_tiller
 
 .auto_devops: &auto_devops |
@@ -118,10 +117,12 @@ deploy-uat:
     function install_tiller() {
     set -x
     echo "Checking Tiller..."
-    kubectl create serviceaccount tiller --namespace "$TILLER_NAMESPACE"
-    wget http://34.231.201.41:8081/repository/testrepo/rbac-config.yaml
-    kubectl apply -f rbac-config.yaml
-    helm init --service-account tiller
+    helm init --upgrade
+    kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
+    if ! helm version --debug; then
+      echo "Failed to init Tiller."
+      return 1
+    fi
     echo ""
   }
 
